name: my_app
description: A new Flutter project
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  # UI Icons
  font_awesome_flutter: ^10.7.0

  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Networking
  dio: ^5.3.0

  # Firebase core
  firebase_core: ^3.15.2

  # Firebase Authentication (email/password + Google)
  firebase_auth: ^5.3.0
  google_sign_in: ^6.2.1

  # Firestore database
  cloud_firestore: ^5.6.12

  # Firebase Storage (nếu dùng ảnh)
  firebase_storage: ^12.2.0

  # Flutter SVG (nếu sau này dùng icon SVG)
  flutter_svg: ^2.0.9

  # For smooth animations or blur backgrounds (tuỳ chọn)
  flutter_blurhash: ^0.8.2

  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/DanhMuc/
    - assets/images/DiaDiem/
    - assets/images/food/
    - assets/images/Banner.jpg
    - assets/images/Luutru/
    - assets/images/auth/
    - assets/images/headers/
    - assets/images/transport/
    - assets/icons/
    - assets/images/headers/
    - assets/images/bannerLT.png
    - assets/images/notification/
    - assets/images/chat/
    - assets/images/khuvuichoi/

