// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKLbKhHccNEmoaVUnOBQL1aZMMGjhj2aE',
    appId: '1:1009510899641:web:a3b48c395bc78f581ba068',
    messagingSenderId: '1009510899641',
    projectId: 'itour-35106',
    authDomain: 'itour-35106.firebaseapp.com',
    storageBucket: 'itour-35106.firebasestorage.app',
    measurementId: 'G-S8NL6WVDJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4xZZBe_-lH0u8RB9V8G7uHL-jEqepmLs',
    appId: '1:1009510899641:android:55d4415a3ab107ba1ba068',
    messagingSenderId: '1009510899641',
    projectId: 'itour-35106',
    storageBucket: 'itour-35106.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4a-dFvnssCTloqi3URmBacr9dE0zNQG8',
    appId: '1:1009510899641:ios:02ad6786587c21e71ba068',
    messagingSenderId: '1009510899641',
    projectId: 'itour-35106',
    storageBucket: 'itour-35106.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKLbKhHccNEmoaVUnOBQL1aZMMGjhj2aE',
    appId: '1:1009510899641:web:69bf5038880cfd6e1ba068',
    messagingSenderId: '1009510899641',
    projectId: 'itour-35106',
    authDomain: 'itour-35106.firebaseapp.com',
    storageBucket: 'itour-35106.firebasestorage.app',
    measurementId: 'G-J2JZX23PSK',
  );

}